server:
  port: 80
  servlet:
    context-path: /api/

spring:
  datasource:
    growth:
      url: jdbc:mysql://localhost:3306/growth?characterEncoding=utf8&useUnicode=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password:

app:
  qiniu:
    filePath: growth/
