server:
  port: 8000
  servlet:
    context-path: /api/

spring:
# 指定默认配置
  profiles:
    active: prod
  datasource:
    url: jdbc:mysql://localhost:3306/growth?characterEncoding=utf8&useUnicode=true&autoReconnectForPools=true&zeroDateTimeBehavior=convertToNull&useSSL=false&includeInnodbStatusInDeadlockExceptions=true
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource

  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 10MB

  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+08

  jpa:
    show-sql: false

  redis:
        database: 1
        host: localhost
        port: 6379
        password:
        jedis:
              pool:
                  max-active: 16
                  max-idle: 16
                  min-idle: 0
                  max-wait: -1
        timeout: 3000

app:
  auth:
      oms-url:
      oms-auth:
  qiniu:
    accessKey: CBLXpYJcUbuJvrTPmzi2Jrwql2_-x_kkd-agdOu4
    secretKey: b5eK7jt_ViGNPL041dsKKEfTU1gMGOZc0ZJb91FT
    bucket: mini-app
    baseUrl: https://img.dahezi.com/
    filePath: growth/dev/
